(()=>{
const PREFIX='ALTA_JSON:';let currentId='';const empty=()=>({alta:false,cert:false,email:'',phone:''});
// El censo base no conservaba plan al leer/guardar una cama. Este módulo lo conserva SOLO cuando contiene ALTA_JSON.
const prevMapBedRow=mapBedRow,prevBedPayload=bedPayload;
mapBedRow=function(r,i){let b=prevMapBedRow(r,i);b.plan=r.plan||'';return b};
bedPayload=function(b){let p=prevBedPayload(b);if(String(b?.plan||'').startsWith(PREFIX))p.plan=b.plan;return p};
function read(b){try{let r=String(b?.plan||'');return r.startsWith(PREFIX)?{...empty(),...JSON.parse(r.slice(PREFIX.length))}:empty()}catch(e){return empty()}}
function selectedBed(){let t=($('title')?.textContent||'').trim(),id=t.replace(/^Cama\s*/i,'').trim();return beds.find(b=>b.id===id)||beds.find(b=>b.id===currentId)}
function css(){let s=document.createElement('style');s.textContent=`.altaVisit{grid-column:1/-1;border:2px solid #86efac;background:#f0fdf4;border-radius:10px;padding:10px}.altaTop{display:flex;align-items:center;justify-content:space-between;font-size:15px;font-weight:900}.altaTop input{width:28px!important;height:28px!important;margin:0!important;accent-color:#15803d}.altaDetails{display:none;margin-top:8px;padding-top:8px;border-top:1px solid #bbf7d0}.altaDetails.on{display:block}.altaBtns{display:flex;gap:7px;margin-top:7px}.altaBtns button{flex:1;min-height:42px}.altaBtns .sel{background:#166534;color:#fff;border-color:#166534}.altaContact{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.altaContact input{margin:0!important}.altaSave{width:100%;margin-top:8px}@media(max-width:600px){.altaContact{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function sync(){let box=$('altaVisit'),b=selectedBed();if(!box)return;if(!b){box.style.display='none';return}currentId=b.id;box.style.display='block';let v=read(b);$('altaCheck').checked=!!v.alta;$('altaDetails').classList.toggle('on',!!v.alta);$('altaYes').classList.toggle('sel',!!v.cert);$('altaNo').classList.toggle('sel',!!v.alta&&!v.cert);$('altaEmail').value=v.email||'';$('altaPhone').value=v.phone||''}
function capture(){let b=selectedBed();if(!b||!$('altaCheck'))return null;let alta=$('altaCheck').checked,cert=alta&&$('altaYes').classList.contains('sel');let v={alta,cert,email:alta?$('altaEmail').value.trim():'',phone:alta?$('altaPhone').value.trim():''};b.plan=PREFIX+JSON.stringify(v);return {b,v}}
async function save(){let x=capture();if(!x)return;let {b}=x;try{setCloudStatus('saving');let {error}=await sb.from('beds').update({plan:b.plan,updated_at:new Date().toISOString(),updated_by:currentUser?.id||null}).eq('id',b.id);if(error)throw error;setCloudStatus('saved')}catch(e){console.error(e);setCloudStatus('error')}}
function install(){let form=$('form');if(!form||$('altaVisit'))return;let box=document.createElement('div');box.id='altaVisit';box.className='altaVisit';box.innerHTML='<label class="altaTop"><span>ALTA</span><input id="altaCheck" type="checkbox"></label><div id="altaDetails" class="altaDetails"><b>¿Necesita certificado?</b><div class="altaBtns"><button type="button" id="altaNo">No</button><button type="button" id="altaYes">Sí</button></div><div id="altaContact" class="altaContact"><input id="altaPhone" type="tel" placeholder="Teléfono"><input id="altaEmail" type="email" placeholder="Correo"></div><button type="button" id="altaSave" class="primary altaSave">Guardar alta</button></div>';let actions=form.querySelector('.actions');form.insertBefore(box,actions||null);$('altaCheck').onchange=e=>{$('altaDetails').classList.toggle('on',e.target.checked);if(!e.target.checked)save()};$('altaNo').onclick=()=>{$('altaNo').classList.add('sel');$('altaYes').classList.remove('sel')};$('altaYes').onclick=()=>{$('altaYes').classList.add('sel');$('altaNo').classList.remove('sel')};$('altaSave').onclick=save;form.addEventListener('submit',()=>capture(),true);$('beds')?.addEventListener('click',()=>setTimeout(sync,20));new MutationObserver(()=>{if(getComputedStyle($('modal')).display!=='none')setTimeout(sync,0)}).observe($('modal'),{attributes:true,attributeFilter:['style']});}
css();install();
})();