(()=>{
const PREFIX='ALTA_JSON:';
let currentAltaBed=null;
function readAlta(b){try{const raw=String(b?.plan||'');if(!raw.startsWith(PREFIX))return {alta:false,cert:false,email:'',phone:''};return {...{alta:false,cert:false,email:'',phone:''},...JSON.parse(raw.slice(PREFIX.length))}}catch(e){return {alta:false,cert:false,email:'',phone:''}}}
function writeAlta(b,v){if(!b||b.id==='601')return;b.plan=PREFIX+JSON.stringify(v)}
function style(){if(document.getElementById('altaStyle'))return;const s=document.createElement('style');s.id='altaStyle';s.textContent=`
.altaVisit{margin:12px 0;padding:12px;border:1px solid #cbd5e1;border-radius:12px;background:#f8fafc}.altaToggle{display:flex;align-items:center;justify-content:space-between;gap:12px;font-weight:900;font-size:15px}.altaToggle input{width:28px;height:28px;accent-color:#15803d}.altaDetails{display:none;margin-top:12px;padding-top:12px;border-top:1px solid #dbe3ee}.altaDetails.on{display:block}.altaCert{display:flex;gap:8px;margin:8px 0}.altaCert button{flex:1;min-height:44px;font-weight:800}.altaCert .sel{background:#166534;color:#fff;border-color:#166534}.altaContact{display:none;grid-template-columns:1fr 1fr;gap:8px}.altaContact.on{display:grid}.altaContact input{width:100%;box-sizing:border-box;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font-size:16px}.altaBadge{display:inline-block;margin-top:6px;padding:3px 7px;border-radius:999px;background:#dcfce7;color:#166534;font-size:10px;font-weight:900}.altaSave{margin-top:10px;width:100%;min-height:44px;font-weight:900}@media(max-width:600px){.altaContact{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function findBed(){if(currentAltaBed){const b=beds.find(x=>x.id===currentAltaBed);if(b)return b}const title=document.querySelector('.modal .modalHead strong,.modal strong');const m=(title?.textContent||'').match(/(?:Cama\s*)?(60(?:1\d|2[0-2]|\d)(?:-[A-D])?|6(?:0[1-9]|1[2-9])(?:-[A-D])?)/);return m?beds.find(x=>x.id===m[1]):null}
function renderBox(){const host=document.getElementById('altaVisit');if(!host)return;const b=findBed();if(!b||!b.type){host.style.display='none';return}host.style.display='block';currentAltaBed=b.id;const v=readAlta(b),details=document.getElementById('altaDetails'),contact=document.getElementById('altaContact');document.getElementById('altaCheck').checked=!!v.alta;details.classList.toggle('on',!!v.alta);contact.classList.toggle('on',!!v.alta&&!!v.cert);document.getElementById('altaYes').classList.toggle('sel',!!v.cert);document.getElementById('altaNo').classList.toggle('sel',v.alta&&!v.cert);document.getElementById('altaEmail').value=v.email||'';document.getElementById('altaPhone').value=v.phone||''}
async function save(){const b=findBed();if(!b||b.id==='601')return;const alta=document.getElementById('altaCheck').checked,cert=document.getElementById('altaYes').classList.contains('sel'),v={alta,cert:alta&&cert,email:alta&&cert?document.getElementById('altaEmail').value.trim():'',phone:alta&&cert?document.getElementById('altaPhone').value.trim():''};writeAlta(b,v);try{setCloudStatus('saving');const {error}=await sb.from('beds').update({plan:b.plan,updated_at:new Date().toISOString(),updated_by:currentUser?.id||null}).eq('id',b.id);if(error)throw error;setCloudStatus('saved');render()}catch(e){console.error(e);setCloudStatus('error')}}
function install(){const modal=document.querySelector('.modalCard,.modal .card,.modalContent');if(!modal)return false;let anchor=document.getElementById('tasksBox')||document.querySelector('[id*=task]')?.parentElement||modal.querySelector('.actions');if(!anchor)return false;const box=document.createElement('div');box.id='altaVisit';box.className='altaVisit';box.innerHTML='<label class="altaToggle"><span>ALTA</span><input id="altaCheck" type="checkbox"></label><div id="altaDetails" class="altaDetails"><b>¿Necesita certificado?</b><div class="altaCert"><button type="button" id="altaNo">No</button><button type="button" id="altaYes">Sí</button></div><div id="altaContact" class="altaContact"><input id="altaEmail" type="email" placeholder="Correo"><input id="altaPhone" type="tel" placeholder="Celular"></div><button type="button" id="altaSave" class="primary altaSave">Guardar alta</button></div>';anchor.parentNode.insertBefore(box,anchor);document.getElementById('altaCheck').onchange=e=>{document.getElementById('altaDetails').classList.toggle('on',e.target.checked);if(!e.target.checked)save()};document.getElementById('altaNo').onclick=()=>{document.getElementById('altaNo').classList.add('sel');document.getElementById('altaYes').classList.remove('sel');document.getElementById('altaContact').classList.remove('on')};document.getElementById('altaYes').onclick=()=>{document.getElementById('altaYes').classList.add('sel');document.getElementById('altaNo').classList.remove('sel');document.getElementById('altaContact').classList.add('on')};document.getElementById('altaSave').onclick=save;new MutationObserver(()=>{if(document.querySelector('.modal')?.style.display!=='none')setTimeout(renderBox,0)}).observe(document.body,{attributes:true,subtree:true,attributeFilter:['style']});return true}
style();let n=0,t=setInterval(()=>{n++;if(install()||n>50)clearInterval(t)},100);
})();