(()=>{
const PREFIX='ALTA_JSON:';let currentId='';const empty=()=>({alta:false,cert:false,email:'',phone:''});
function read(b){try{let r=String(b?.plan||'');return r.startsWith(PREFIX)?{...empty(),...JSON.parse(r.slice(PREFIX.length))}:empty()}catch(e){return empty()}}
function selectedBed(){let t=($('title')?.textContent||'').trim(),id=t.replace(/^Cama\s*/i,'').trim();return beds.find(b=>b.id===id)||beds.find(b=>b.id===currentId)}
function css(){let s=document.createElement('style');s.textContent=`.altaVisit{grid-column:1/-1;border:2px solid #86efac;background:#f0fdf4;border-radius:10px;padding:10px}.altaTop{display:flex;align-items:center;justify-content:space-between;font-size:15px;font-weight:900}.altaTop input{width:28px!important;height:28px!important;margin:0!important;accent-color:#15803d}.altaDetails{display:none;margin-top:8px;padding-top:8px;border-top:1px solid #bbf7d0}.altaDetails.on{display:block}.altaBtns{display:flex;gap:7px;margin-top:7px}.altaBtns button{flex:1;min-height:42px}.altaBtns .sel{background:#166534;color:#fff;border-color:#166534}.altaContact{display:none;grid-template-columns:1fr 1fr;gap:7px;margin-top:7px}.altaContact.on{display:grid}.altaContact input{margin:0!important}.altaSave{width:100%;margin-top:8px}@media(max-width:600px){.altaContact{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function sync(){let box=$('altaVisit'),b=selectedBed();if(!box)return;if(!b){box.style.display='none';return}currentId=b.id;box.style.display='block';let v=read(b);$('altaCheck').checked=!!v.alta;$('altaDetails').classList.toggle('on',!!v.alta);$('altaYes').classList.toggle('sel',!!v.cert);$('altaNo').classList.toggle('sel',!!v.alta&&!v.cert);$('altaContact').classList.toggle('on',!!v.alta&&!!v.cert);$('altaEmail').value=v.email||'';$('altaPhone').value=v.phone||''}
async function save(){let b=selectedBed();if(!b)return;let alta=$('altaCheck').checked,cert=alta&&$('altaYes').classList.contains('sel');let v={alta,cert,email:cert?$('altaEmail').value.trim():'',phone:cert?$('altaPhone').value.trim():''};b.plan=PREFIX+JSON.stringify(v);try{setCloudStatus('saving');let {error}=await sb.from('beds').update({plan:b.plan,updated_at:new Date().toISOString(),updated_by:currentUser?.id||null}).eq('id',b.id);if(error)throw error;setCloudStatus('saved')}catch(e){console.error(e);setCloudStatus('error')}}
function install(){let form=$('form');if(!form||$('altaVisit'))return;let box=document.createElement('div');box.id='altaVisit';box.className='altaVisit';box.innerHTML='<label class="altaTop"><span>ALTA</span><input id="altaCheck" type="checkbox"></label><div id="altaDetails" class="altaDetails"><b>¿Necesita certificado?</b><div class="altaBtns"><button type="button" id="altaNo">No</button><button type="button" id="altaYes">Sí</button></div><div id="altaContact" class="altaContact"><input id="altaEmail" type="email" placeholder="Correo"><input id="altaPhone" type="tel" placeholder="Celular"></div><button type="button" id="altaSave" class="primary altaSave">Guardar alta</button></div>';let actions=form.querySelector('.actions');form.insertBefore(box,actions||null);$('altaCheck').onchange=e=>{$('altaDetails').classList.toggle('on',e.target.checked);if(!e.target.checked)save()};$('altaNo').onclick=()=>{$('altaNo').classList.add('sel');$('altaYes').classList.remove('sel');$('altaContact').classList.remove('on')};$('altaYes').onclick=()=>{$('altaYes').classList.add('sel');$('altaNo').classList.remove('sel');$('altaContact').classList.add('on')};$('altaSave').onclick=save;
$('beds')?.addEventListener('click',()=>setTimeout(sync,20));new MutationObserver(()=>{if(getComputedStyle($('modal')).display!=='none')setTimeout(sync,0)}).observe($('modal'),{attributes:true,attributeFilter:['style']});}
css();install();
})();