(()=>{
const PREFIX='DOCTORS_JSON:';
const DEFAULT_CONFIG={doctors:[
 {id:'boza',name:'Dra. Boza',beds:['601','602','603-A','603-B','607-A','607-B','608-A','608-B','608-C','612','613','614-A','614-B','615-A']},
 {id:'andagoya',name:'Dra. Andagoya',beds:['604-A','604-B','604-C','604-D','606-A','606-B','608-D','609-A','609-B','609-C','609-D','615-B','615-C','615-D','616-A','616-B']},
 {id:'pita',name:'Dra. Pita',beds:['605-A','605-B','605-C','605-D','6010-A','6010-B','6010-C','6010-D','6011-A','6011-B','616-C','616-D','617-A','617-B','618-A','618-B','619-A','619-B']}
]};
let doctorConfig=JSON.parse(JSON.stringify(DEFAULT_CONFIG)),doctorView='residentes',configLoaded=false,managerOpen=false;
const baseFilteredBeds=filteredBeds,baseRender=render,baseRenderHandoff=renderHandoff,baseBedPayload=bedPayload;
function docById(id){return doctorConfig.doctors.find(d=>d.id===id)}
function assignedSet(){let d=docById(doctorView);return new Set(d?d.beds:[])}
function scopedBeds(){if(doctorView==='residentes')return beds;let s=assignedSet();return beds.filter(b=>s.has(b.id))}
function injectStyle(){let s=document.createElement('style');s.textContent=`
.doctorBar{display:flex;gap:7px;align-items:center;overflow:auto;padding:9px 12px;background:#fff;border-bottom:1px solid #dde3ec;position:sticky;top:0;z-index:9}.doctorBar button{white-space:nowrap;padding:8px 11px}.doctorBar .docActive{background:#0f766e;color:#fff;border-color:#0f766e;font-weight:800}.doctorStats{font-size:11px;color:#64748b;white-space:nowrap;margin-left:auto}.doctorManage{font-size:12px}.doctorMode .tabs,.doctorMode .sum{display:none!important}.doctorMode main{padding-top:8px}.doctorMode .grid{grid-template-columns:repeat(2,minmax(0,1fr))}.doctorMode .bed{min-height:0;padding:12px}.doctorPendingBox{margin-top:9px;padding:8px;background:#fff7ed;border:1px solid #fed7aa;border-radius:8px;text-align:left;font-size:11px;line-height:1.35}.doctorPendingBox b{display:block;margin-bottom:3px}.doctorPendingItem{margin:3px 0}.doctorPendingItem.over{color:#b42318;font-weight:800}.doctorNoPending{color:#166534;background:#f0fdf4;border-color:#bbf7d0}.doctorModal{display:none;position:fixed;inset:0;background:#0008;z-index:90;padding:10px;overflow:auto}.doctorPanel{max-width:900px;margin:12px auto;background:#fff;border-radius:16px;overflow:hidden}.doctorHead{display:flex;align-items:center;gap:8px;padding:14px;border-bottom:1px solid #e2e8f0;position:sticky;top:0;background:#fff;z-index:2}.doctorHead strong{flex:1}.doctorBody{padding:14px}.doctorRow{border:1px solid #dbe3ee;border-radius:12px;padding:11px;margin-bottom:10px}.doctorRowTop{display:flex;gap:8px;align-items:center}.doctorRowTop input{flex:1;border:1px solid #cbd5e1;border-radius:9px;padding:9px;font-size:15px}.bedChecks{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px;margin-top:9px}.bedCheck{display:flex;align-items:center;gap:5px;font-size:11px;padding:5px;border:1px solid #e2e8f0;border-radius:7px}.doctorActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.doctorHint{font-size:11px;color:#64748b;margin-bottom:10px}
@media(max-width:600px){.doctorBar{top:0;padding:7px}.doctorStats{display:none}.doctorMode .grid{grid-template-columns:1fr}.bedChecks{grid-template-columns:repeat(2,minmax(0,1fr))}.doctorRowTop{align-items:stretch;flex-wrap:wrap}.doctorRowTop input{min-width:190px}}
@media(min-width:900px){.doctorMode .grid{grid-template-columns:repeat(3,minmax(0,1fr))}}
`;document.head.appendChild(s)}
function injectUI(){let bar=document.createElement('div');bar.id='doctorBar';bar.className='doctorBar';document.body.insertBefore(bar,document.querySelector('header'));
let modal=document.createElement('div');modal.id='doctorManager';modal.className='doctorModal';modal.innerHTML='<div class="doctorPanel"><div class="doctorHead"><strong>Administrar doctoras y camas</strong><button id="closeDoctorManager">✕</button></div><div class="doctorBody"><div class="doctorHint">Residentes siempre conserva acceso a todas las camas. Cada cama puede asignarse a una sola doctora.</div><div id="doctorRows"></div><div class="doctorActions"><button type="button" id="addDoctor">+ Agregar doctora</button><button type="button" class="primary" id="saveDoctors">Guardar cambios</button></div></div></div>';document.body.appendChild(modal);
$('closeDoctorManager').onclick=closeManager;$('addDoctor').onclick=addDoctor;$('saveDoctors').onclick=saveManager;
modal.addEventListener('click',e=>{if(e.target===modal)closeManager()});}
function doctorStatsText(){if(doctorView==='residentes')return'Vista general · '+beds.filter(b=>b.type).length+' pacientes';let list=scopedBeds(),occ=list.filter(b=>b.type),pend=occ.flatMap(b=>b.tasks||[]).filter(t=>taskStatus(t)!=='done'),over=pend.filter(t=>taskStatus(t)==='overdue');return occ.length+' pacientes · '+pend.length+' pendientes'+(over.length?' · '+over.length+' vencidos':'')}
function renderDoctorBar(){let bar=$('doctorBar');if(!bar)return;let html='<button data-doc="residentes" class="'+(doctorView==='residentes'?'docActive':'')+'">Residentes</button>'+doctorConfig.doctors.map(d=>'<button data-doc="'+esc(d.id)+'" class="'+(doctorView===d.id?'docActive':'')+'">'+esc(d.name)+'</button>').join('')+'<span class="doctorStats">'+esc(doctorStatsText())+'</span>'+(doctorView==='residentes'?'<button class="doctorManage" id="manageDoctors">⚙️ Doctoras</button>':'');bar.innerHTML=html;bar.querySelectorAll('[data-doc]').forEach(b=>b.onclick=()=>selectDoctor(b.dataset.doc));let m=$('manageDoctors');if(m)m.onclick=openManager}
function selectDoctor(id){doctorView=id;if(id==='residentes'){document.body.classList.remove('doctorMode');filter='sector'}else{document.body.classList.add('doctorMode');filter='all';$('search').value=''}render();let hb=$('handoff');if(hb)hb.textContent=id==='residentes'?'📋 Entrega de guardia':'📋 Entrega / PDF · '+(docById(id)?.name||'Doctora')}
filteredBeds=function(){let list=baseFilteredBeds();if(doctorView==='residentes')return list;let s=assignedSet();return list.filter(b=>s.has(b.id))};
function enhanceDoctorCards(){if(doctorView==='residentes')return;let set=assignedSet();$('beds').querySelectorAll('.bed').forEach(btn=>{let id=(btn.querySelector('.id')?.textContent||'').replace(/^Cama\s+/,'').trim(),b=beds.find(x=>x.id===id);if(!b||!set.has(id)||!b.type)return;let pending=(b.tasks||[]).filter(t=>taskStatus(t)!=='done').sort((a,z)=>taskStatus(a)==='overdue'?-1:1);let box=document.createElement('div');box.className='doctorPendingBox '+(!pending.length?'doctorNoPending':'');if(!pending.length)box.innerHTML='<b>✓ Sin pendientes activos</b>';else box.innerHTML='<b>Pendientes</b>'+pending.slice(0,4).map(t=>'<div class="doctorPendingItem '+(taskStatus(t)==='overdue'?'over':'')+'">'+(taskStatus(t)==='overdue'?'VENCIDO · ':'')+esc(t.text)+(t.date?' · '+esc(fmtDate(t.date)):'')+(t.time?' '+esc(t.time):'')+'</div>').join('')+(pending.length>4?'<div>+'+(pending.length-4)+' más</div>':'');btn.appendChild(box)})}
render=function(){baseRender();if(doctorView!=='residentes'){let scope=scopedBeds(),occ=scope.filter(b=>b.type),pend=scope.flatMap(b=>b.tasks||[]).filter(t=>taskStatus(t)!=='done'),over=pend.filter(t=>taskStatus(t)==='overdue').length;$('all').textContent='Mis camas · '+scope.length;$('occ').textContent=occ.length+' ocupadas';$('free').textContent=(scope.length-occ.length)+' disponibles';$('pend').textContent=pend.length+' pendientes'+(over?' · '+over+' vencidos':'');enhanceDoctorCards()}renderDoctorBar()};
renderHandoff=function(){if(doctorView==='residentes'){baseRenderHandoff();let s=document.querySelector('.handoffHead strong');if(s)s.textContent='📋 Entrega de guardia — Residentes';return}let original=beds;try{beds=scopedBeds();baseRenderHandoff();let s=document.querySelector('.handoffHead strong'),d=docById(doctorView);if(s)s.textContent='📋 Entrega de guardia — '+(d?d.name:'Doctora')}finally{beds=original}};
bedPayload=function(b){let p=baseBedPayload(b);if(b.id==='601'&&configLoaded)p.plan=PREFIX+JSON.stringify(doctorConfig);return p};
async function loadDoctorConfig(){if(!currentUser)return;try{let {data,error}=await sb.from('beds').select('plan').eq('id','601').single();if(error)throw error;let raw=String(data?.plan||'');if(raw.startsWith(PREFIX)){let parsed=JSON.parse(raw.slice(PREFIX.length));if(parsed&&Array.isArray(parsed.doctors))doctorConfig=parsed}else await saveDoctorConfig();configLoaded=true;render()}catch(e){console.error('doctor config',e)}}
async function saveDoctorConfig(){let {error}=await sb.from('beds').update({plan:PREFIX+JSON.stringify(doctorConfig),updated_at:new Date().toISOString(),updated_by:currentUser?currentUser.id:null}).eq('id','601');if(error)throw error;configLoaded=true}
function openManager(){managerOpen=true;renderManager();$('doctorManager').style.display='block'}function closeManager(){managerOpen=false;$('doctorManager').style.display='none'}
function renderManager(){let box=$('doctorRows');box.innerHTML='';doctorConfig.doctors.forEach((d,i)=>{let row=document.createElement('div');row.className='doctorRow';row.dataset.i=i;row.innerHTML='<div class="doctorRowTop"><input class="doctorName" value="'+esc(d.name)+'" aria-label="Nombre doctora"><button type="button" class="danger removeDoctor">Eliminar</button></div><div class="bedChecks">'+BED_IDS.map(id=>'<label class="bedCheck"><input type="checkbox" data-bed="'+esc(id)+'" '+(d.beds.includes(id)?'checked':'')+'> '+esc(id)+'</label>').join('')+'</div>';box.appendChild(row)});box.querySelectorAll('input[type=checkbox]').forEach(cb=>cb.onchange=()=>{if(!cb.checked)return;let bed=cb.dataset.bed;box.querySelectorAll('input[data-bed="'+CSS.escape(bed)+'"]').forEach(other=>{if(other!==cb)other.checked=false})});box.querySelectorAll('.removeDoctor').forEach((b,i)=>b.onclick=()=>{if(!confirm('¿Eliminar esta doctora de la lista? Las camas quedarán sin asignar.'))return;doctorConfig.doctors.splice(i,1);renderManager()})}
function addDoctor(){doctorConfig.doctors.push({id:'doc_'+Date.now(),name:'Nueva doctora',beds:[]});renderManager();let ins=$('doctorRows').lastElementChild?.querySelector('.doctorName');if(ins){ins.focus();ins.select()}}
async function saveManager(){let rows=[...$('doctorRows').querySelectorAll('.doctorRow')],used=new Set();doctorConfig.doctors=rows.map((row,i)=>{let old=doctorConfig.doctors[i]||{},name=row.querySelector('.doctorName').value.trim()||'Doctora',beds=[...row.querySelectorAll('input[data-bed]:checked')].map(x=>x.dataset.bed).filter(id=>{if(used.has(id))return false;used.add(id);return true});return{id:old.id||('doc_'+Date.now()+'_'+i),name,beds}});try{cloudMsg('☁️ Guardando doctoras…');await saveDoctorConfig();cloudMsg('☁️ Guardado');closeManager();render()}catch(e){console.error(e);cloudMsg('☁️ No se pudo guardar',true);alert('No se pudo guardar la distribución de doctoras.')}}
injectStyle();injectUI();renderDoctorBar();
let wait=setInterval(()=>{if(currentUser){clearInterval(wait);loadDoctorConfig();setInterval(()=>{if(currentUser&&!managerOpen)loadDoctorConfig()},30000)}},500);
})();