(()=>{
if(document.getElementById('dischargeRegistryBtn'))return;
const demo=document.querySelector('.demo');if(!demo)return;
const btn=document.createElement('button');btn.id='dischargeRegistryBtn';btn.type='button';btn.textContent='📊 Registro altas / prealtas';demo.insertBefore(btn,demo.firstChild);
const modal=document.createElement('div');modal.id='dischargeRegistryModal';modal.style.cssText='display:none;position:fixed;inset:0;background:#0008;z-index:120;padding:10px;overflow:auto';modal.innerHTML='<div style="background:#fff;max-width:1180px;margin:10px auto;border-radius:16px;overflow:hidden"><div style="display:flex;gap:8px;align-items:center;padding:14px;border-bottom:1px solid #e2e8f0"><strong style="flex:1">Registro de altas y prealtas · Puérperas</strong><button type="button" id="closeRegistry">✕</button></div><div style="padding:12px;overflow:auto"><div id="registryInfo" style="font-size:11px;color:#64748b;margin-bottom:8px"></div><table id="registryTable" style="width:100%;border-collapse:collapse;font-size:12px;min-width:980px"><thead><tr><th>Cama</th><th>Paciente</th><th>Historia clínica</th><th>Cédula</th><th>Diagnóstico CIE-10</th><th>Fecha de ingreso al servicio</th><th>Días en HO</th><th>Pre-alta</th><th>Alta</th><th>Observación</th></tr></thead><tbody></tbody></table></div></div>';document.body.appendChild(modal);
const style=document.createElement('style');style.textContent='#registryTable th,#registryTable td{border:1px solid #cbd5e1;padding:7px;vertical-align:top}#registryTable th{background:#eef2f7;font-size:11px;text-align:center;white-space:nowrap}';document.head.appendChild(style);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const readAlta=b=>{try{const p=String(b.plan||'');return p.startsWith('ALTA_JSON:')&&!!JSON.parse(p.slice(10)).alta}catch(e){return false}};
const fmt=v=>{if(!v)return '';const d=new Date(v);return isNaN(d)?'':d.toLocaleString('es-EC',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})};
const day=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const days=v=>{if(!v)return '';const d=new Date(v);return isNaN(d)?'':Math.max(0,Math.floor((day(new Date())-day(d))/86400000))};
const cie=b=>b.birthType==='parto'?'O80.9':b.birthType==='cesarea'?'O82.1':'';
function preAlta(b){if(readAlta(b)||!b.eventDate||!b.birthType)return '';const p=String(b.eventDate).split('-').map(Number);if(p.length!==3)return '';let ref=new Date(p[0],p[1]-1,p[2]);const hm=String(b.eventTime||'00:00').split(':').map(Number),mins=(hm[0]||0)*60+(hm[1]||0);if(mins>=960)ref.setDate(ref.getDate()+1);ref.setDate(ref.getDate()+(b.birthType==='cesarea'?2:1));return day(new Date())>=day(ref)?'SÍ':''}
function render(){const data=beds.filter(b=>b.type==='puer');document.querySelector('#registryTable tbody').innerHTML=data.map(b=>`<tr><td>${esc(b.id)}</td><td>${esc(b.name||'')}</td><td>${esc(b.hc||'')}</td><td>${esc(b.cedula||'')}</td><td>${esc(cie(b))}</td><td>${esc(fmt(b.admission_at))}</td><td>${esc(days(b.admission_at))}</td><td>${esc(preAlta(b))}</td><td>${readAlta(b)?'SÍ':''}</td><td></td></tr>`).join('');document.getElementById('registryInfo').textContent='Solo puérperas hospitalizadas. CIE-10 automático: parto O80.9 · cesárea O82.1. Pre-alta: parto 24 h / cesárea 48 h; nacimientos desde las 16:00 comienzan conteo al día siguiente.'}
btn.onclick=()=>{render();modal.style.display='block'};document.getElementById('closeRegistry').onclick=()=>modal.style.display='none';
})();