(()=>{
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function alta(b){try{const p=String(b.plan||'');return p.startsWith('ALTA_JSON:')&&!!JSON.parse(p.slice(10)).alta}catch(e){return false}}
function fmt(v){if(!v)return '';const d=new Date(v);return isNaN(d)?'':d.toLocaleString('es-EC',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function d0(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function dias(v){if(!v)return '';const d=new Date(v);return isNaN(d)?'':Math.max(0,Math.floor((d0(new Date())-d0(d))/86400000))}
function cie(b){return b.birthType==='parto'?'O80.9':b.birthType==='cesarea'?'O82.1':''}
function pre(b){if(alta(b)||!b.eventDate||!b.birthType)return '';const p=String(b.eventDate).split('-').map(Number);if(p.length!==3)return '';let r=new Date(p[0],p[1]-1,p[2]);const hm=String(b.eventTime||'00:00').split(':').map(Number);if((hm[0]||0)*60+(hm[1]||0)>=960)r.setDate(r.getDate()+1);r.setDate(r.getDate()+(b.birthType==='cesarea'?2:1));return d0(new Date())>=d0(r)?'SÍ':''}
function fila(b){return [b.id,b.name||'',b.hc||'',b.cedula||'',cie(b),fmt(b.admission_at),dias(b.admission_at),pre(b),alta(b)?'SÍ':'','']}
function guardar(){const data=beds.filter(b=>b.type==='puer');if(!data.length)return alert('No hay puérperas hospitalizadas para guardar.');const h=['CAMA','PACIENTE','HISTORIA CLÍNICA','CÉDULA','DIAGNÓSTICO CIE-10','FECHA DE INGRESO AL SERVICIO','DÍAS EN HO','PRE-ALTA','ALTA','OBSERVACIÓN'];const rows=data.map(b=>'<tr>'+fila(b).map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('');const doc='<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="UTF-8"><style>body{font-family:Arial}table{border-collapse:collapse;font-size:10pt}td,th{border:1px solid #000;padding:6px;vertical-align:middle}h2{text-align:center}th{background:#d9e2f3;font-weight:bold;text-align:center}td:nth-child(2),td:nth-child(10){min-width:180px}td:nth-child(6){min-width:150px}</style></head><body><h2>REGISTRO DE ALTAS Y PREALTAS</h2><table><tr>'+h.map(x=>'<th>'+x+'</th>').join('')+'</tr>'+rows+'</table></body></html>';const blob=new Blob(['\ufeff',doc],{type:'application/vnd.ms-excel'}),a=document.createElement('a'),n=new Date(),p=x=>String(x).padStart(2,'0');a.href=URL.createObjectURL(blob);a.download='Registro_altas_prealtas_'+n.getFullYear()+'-'+p(n.getMonth()+1)+'-'+p(n.getDate())+'.xls';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function install(){const close=document.getElementById('closeRegistry');if(!close||document.getElementById('saveRegistryExcel'))return;const b=document.createElement('button');b.id='saveRegistryExcel';b.type='button';b.className='primary';b.textContent='📥 Guardar en Excel';b.onclick=guardar;close.parentNode.insertBefore(b,close)}
install();setTimeout(install,500);
})();