(()=>{
function alta(b){try{const p=String(b.plan||'');return p.startsWith('ALTA_JSON:')&&!!JSON.parse(p.slice(10)).alta}catch(e){return false}}
function fmtFecha(v){if(!v)return '';const d=new Date(v);if(isNaN(d))return '';return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()}
function d0(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function dias(v){if(!v)return '';const d=new Date(v);return isNaN(d)?'':Math.max(0,Math.floor((d0(new Date())-d0(d))/86400000))}
function cie(b){return b.birthType==='parto'?'O80.9':b.birthType==='cesarea'?'O82.1':''}
function pre(b){if(alta(b)||!b.eventDate||!b.birthType)return '';const p=String(b.eventDate).split('-').map(Number);if(p.length!==3)return '';let r=new Date(p[0],p[1]-1,p[2]);const hm=String(b.eventTime||'00:00').split(':').map(Number);if((hm[0]||0)*60+(hm[1]||0)>=960)r.setDate(r.getDate()+1);r.setDate(r.getDate()+(b.birthType==='cesarea'?2:1));return d0(new Date())>=d0(r)?'X':''}
const xe=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function col(n){let s='';for(;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function crc32(u){let c=-1;for(const b of u){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xEDB88320:0)}return(c^-1)>>>0}
function u16(a,v){a.push(v&255,(v>>>8)&255)}function u32(a,v){a.push(v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255)}
function zip(files){const enc=new TextEncoder(),out=[],central=[];let off=0;for(const f of files){const name=enc.encode(f.name),data=enc.encode(f.data),crc=crc32(data),h=[];u32(h,0x04034b50);u16(h,20);u16(h,0);u16(h,0);u16(h,0);u16(h,0);u32(h,crc);u32(h,data.length);u32(h,data.length);u16(h,name.length);u16(h,0);const chunk=new Uint8Array(h.length+name.length+data.length);chunk.set(h);chunk.set(name,h.length);chunk.set(data,h.length+name.length);out.push(chunk);const c=[];u32(c,0x02014b50);u16(c,20);u16(c,20);u16(c,0);u16(c,0);u16(c,0);u16(c,0);u32(c,crc);u32(c,data.length);u32(c,data.length);u16(c,name.length);u16(c,0);u16(c,0);u16(c,0);u16(c,0);u32(c,0);u32(c,off);const cc=new Uint8Array(c.length+name.length);cc.set(c);cc.set(name,c.length);central.push(cc);off+=chunk.length}const cs=central.reduce((n,x)=>n+x.length,0),end=[];u32(end,0x06054b50);u16(end,0);u16(end,0);u16(end,files.length);u16(end,files.length);u32(end,cs);u32(end,off);u16(end,0);return new Blob([...out,...central,new Uint8Array(end)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function cell(ref,v,style){const num=typeof v==='number'&&Number.isFinite(v);return num?'<c r="'+ref+'" s="'+style+'"><v>'+v+'</v></c>':'<c r="'+ref+'" s="'+style+'" t="inlineStr"><is><t xml:space="preserve">'+xe(v)+'</t></is></c>'}
function guardar(){
 const data=beds.filter(b=>b.type==='puer');if(!data.length)return alert('No hay puérperas hospitalizadas para guardar.');
 const headers=['CAMA','PACIENTE','HISTORIA\nCLÍNICA','CÉDULA','DIAGNÓSTICO\nCON CIE10','FECHA DE\nINGRESO\nAL SERVICIO','DÍAS EN HO','PRE-ALTA','ALTA','OBSERVACIÓN'];
 const rows=data.map(b=>[b.id,b.name||'',b.hc||'',b.cedula||'',cie(b),fmtFecha(b.admission_at),dias(b.admission_at),pre(b),alta(b)?'X':'','']);
 let xmlRows='';
 const top=[
  ['INSTITUTO ECUATORIANO DE SEGURIDAD SOCIAL','Código:','FO-SH-HO-002'],
  ['HOSPITAL GENERAL DEL NORTE DE GUAYAQUIL LOS CEIBOS','Fecha:','1/1/2026'],
  ['SERVICIOS HOSPITALARIOS','Versión:','1']
 ];
 top.forEach((r,i)=>{const rr=i+1;xmlRows+='<row r="'+rr+'" ht="21" customHeight="1">'+cell('A'+rr,r[0],3)+cell('I'+rr,r[1],4)+cell('J'+rr,r[2],4)+'</row>'});
 xmlRows+='<row r="4" ht="24" customHeight="1">'+cell('A4','REGISTRO DE INGRESO DE PACIENTES AL SERVICIO DE HOSPITALIZACIÓN',5)+'</row>';
 xmlRows+='<row r="5" ht="54" customHeight="1">'+headers.map((h,i)=>cell(col(i+1)+'5',h,1)).join('')+'</row>';
 rows.forEach((r,ri)=>{const rr=ri+6;xmlRows+='<row r="'+rr+'" ht="22" customHeight="1">'+r.map((v,ci)=>cell(col(ci+1)+rr,v,ci===1?7:(ci>=6&&ci<=8?8:2))).join('')+'</row>'});
 const widths=[10,34,17,17,19,20,12,12,10,30].map((w,i)=>'<col min="'+(i+1)+'" max="'+(i+1)+'" width="'+w+'" customWidth="1"/>').join('');
 const merges='<mergeCells count="4"><mergeCell ref="A1:H1"/><mergeCell ref="A2:H2"/><mergeCell ref="A3:H3"/><mergeCell ref="A4:J4"/></mergeCells>';
 const files=[
 {name:'[Content_Types].xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>'},
 {name:'_rels/.rels',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'},
 {name:'xl/workbook.xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Registro" sheetId="1" r:id="rId1"/></sheets></workbook>'},
 {name:'xl/_rels/workbook.xml.rels',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'},
 {name:'xl/styles.xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="4"><font><sz val="10"/><name val="Arial"/></font><font><b/><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="10"/><name val="Arial"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Arial"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FFE7E6E6"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FF1F365C"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FF7F7F7F"/></left><right style="thin"><color rgb="FF7F7F7F"/></right><top style="thin"><color rgb="FF7F7F7F"/></top><bottom style="thin"><color rgb="FF7F7F7F"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="9"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="3" fillId="3" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="3" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="3" fillId="3" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center" wrapText="1"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1"><alignment horizontal="center" vertical="center"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'},
 {name:'xl/worksheets/sheet1.xml',data:'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="5" topLeftCell="A6" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>'+widths+'</cols><sheetData>'+xmlRows+'</sheetData>'+merges+'<pageMargins left="0.25" right="0.25" top="0.35" bottom="0.35" header="0.2" footer="0.2"/><pageSetup orientation="landscape" fitToWidth="1" fitToHeight="0"/></worksheet>'}
 ];
 const blob=zip(files),url=URL.createObjectURL(blob),a=document.createElement('a'),n=new Date(),p=x=>String(x).padStart(2,'0');a.href=url;a.download='Registro_ingreso_hospitalizacion_'+n.getFullYear()+'-'+p(n.getMonth()+1)+'-'+p(n.getDate())+'.xlsx';a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);
}
function install(){const close=document.getElementById('closeRegistry');if(!close||document.getElementById('saveRegistryExcel'))return;const b=document.createElement('button');b.id='saveRegistryExcel';b.type='button';b.className='primary';b.textContent='📥 Guardar en Excel (.xlsx)';b.onclick=guardar;close.parentNode.insertBefore(b,close)}
install();setTimeout(install,500);
})();